knowledge_sources:
  YFINANCE:
    name: yfinance
    type: function
    description: yfinance provides financial data for companies.
    functions_package: yfinance_functions
    override_reliability: A
    override_credibility: "1"
